#!/bin/sh

BRANCH=${1:-master}
ARCHIVE_NAME=tmp/FlickSKK
PROVISIONING_PROFILE=FlickSKK

PRETTY=cat
if which xcpretty; then
  PRETTY=xcpretty
fi

echo "cleanup" && \
rm -rf tmp && mkdir tmp && \
echo "apply icon" && \
git checkout $BRANCH && \
git rebase master && \
echo "build archive" && \
xcodebuild archive -workspace FlickSKK.xcworkspace -scheme FlickSKK -archivePath $ARCHIVE_NAME  | $PRETTY && \
echo "create ipa" && \
xcodebuild -exportArchive -archivePath $ARCHIVE_NAME.xcarchive -exportPath $ARCHIVE_NAME -exportFormat ipa | $PRETTY && \
echo "Go to testflight" && \
git checkout master && \
open -a TestFlight $ARCHIVE_NAME.ipa
